import { promises as fs } from "node:fs";
import path from "node:path";

import { readGenesisLibrary } from "./library";
import { getFrozenRuntimeParameters } from "./runtime-index";

const OUTPUT_DIR = path.join(process.cwd(), "docs", "v3-parameter-catalog");
const RAW_BASE = "https://raw.githubusercontent.com/kleafrog-source/meta-crystal-abstract-researcher/main/docs/v3-parameter-catalog";

export interface V3CatalogResult {
  generated_at: string;
  parameter_count: number;
  part_size: number;
  part_count: number;
  files: Array<{ name: string; count: number; raw_url: string }>;
  output_dir: string;
}

function cleanHeading(value: unknown, fallback: string): string {
  const text = typeof value === "string" ? value.trim() : "";
  return (text || fallback).replaceAll(/\r?\n/g, " ");
}

export async function generateV3TechnicalNameCatalog(partSize = 500): Promise<V3CatalogResult> {
  const safePartSize = Math.max(100, Math.min(1000, Math.trunc(partSize)));
  const [{ parameters: frozen }, library] = await Promise.all([
    getFrozenRuntimeParameters(),
    readGenesisLibrary(),
  ]);
  const byName = new Map<string, Record<string, unknown>>();
  for (const parameter of frozen) {
    if (parameter.technical_name) byName.set(parameter.technical_name, parameter as unknown as Record<string, unknown>);
  }
  for (const parameter of library) {
    if (parameter.technical_name) byName.set(parameter.technical_name, parameter);
  }
  const parameters = [...byName.values()].sort((left, right) => {
    const leftKey = `${cleanHeading(left.category, "uncategorized")}\u0000${cleanHeading(left.sub_category, "general")}\u0000${String(left.technical_name)}`;
    const rightKey = `${cleanHeading(right.category, "uncategorized")}\u0000${cleanHeading(right.sub_category, "general")}\u0000${String(right.technical_name)}`;
    return leftKey.localeCompare(rightKey, "en");
  });

  await fs.mkdir(OUTPUT_DIR, { recursive: true });
  const oldParts = (await fs.readdir(OUTPUT_DIR)).filter((name) => /^part-\d{3}\.md$/.test(name));
  await Promise.all(oldParts.map((name) => fs.rm(path.join(OUTPUT_DIR, name), { force: true })));

  const generatedAt = new Date().toISOString();
  const files: V3CatalogResult["files"] = [];
  for (let offset = 0; offset < parameters.length; offset += safePartSize) {
    const slice = parameters.slice(offset, offset + safePartSize);
    const name = `part-${String(files.length + 1).padStart(3, "0")}.md`;
    const lines = [
      `# V3 technical names · part ${files.length + 1}`,
      "",
      `Generated: ${generatedAt}`,
      "",
    ];
    let previousGroup = "";
    for (const parameter of slice) {
      const category = cleanHeading(parameter.category, "uncategorized");
      const subCategory = cleanHeading(parameter.sub_category, "general");
      const group = `${category}\u0000${subCategory}`;
      if (group !== previousGroup) {
        lines.push(`## ${category} / ${subCategory}`, "");
        previousGroup = group;
      }
      lines.push(`- ${String(parameter.technical_name)}`);
    }
    lines.push("");
    await fs.writeFile(path.join(OUTPUT_DIR, name), lines.join("\n"), "utf8");
    files.push({ name, count: slice.length, raw_url: `${RAW_BASE}/${name}` });
  }

  const readme = [
    "# Flowmusic Genesis V3 · technical-name catalog",
    "",
    "Generated by Combinatorial Genesis from the current autonomous library and frozen V3 dataset.",
    "Each list item contains only a `technical_name`; headings preserve category/sub-category context.",
    "",
    `- Generated: ${generatedAt}`,
    `- Parameters: ${parameters.length}`,
    `- Parts: ${files.length}`,
    `- Maximum names per part: ${safePartSize}`,
    "",
    ...files.flatMap((file) => [`- [${file.name}](${file.name}) · ${file.count} names`, `  - Raw: ${file.raw_url}`]),
    "",
  ];
  await fs.writeFile(path.join(OUTPUT_DIR, "README.md"), readme.join("\n"), "utf8");
  const result = {
    generated_at: generatedAt,
    parameter_count: parameters.length,
    part_size: safePartSize,
    part_count: files.length,
    files,
    output_dir: OUTPUT_DIR,
  };
  await fs.writeFile(path.join(OUTPUT_DIR, "manifest.json"), `${JSON.stringify(result, null, 2)}\n`, "utf8");
  return result;
}
