/**
 * Re-export of lucide-react icons used throughout the app.
 * Centralizes icon imports so we can swap or alias icons in one place.
 */
export {
  Gem,
  FlaskConical,
  Workflow,
  Library,
  Download,
  Sparkles,
  MessageSquare,
  Settings,
  LayoutDashboard,
  Search,
  Play,
  Square,
  Plus,
  Minus,
  Trash2,
  RefreshCw,
  Save,
  Upload,
  FileJson,
  Send,
  Loader2,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Info,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  Star,
  Brain,
  Cpu,
  Database,
  Activity,
  Zap,
  Code2,
  Eye,
  Pencil,
  Copy,
  X,
  Filter,
  ArrowUpRight,
  ArrowDownRight,
  CircleDot,
  Layers,
  Hash,
  Calendar,
  Tag,
  TrendingUp,
  Lightbulb,
  FileText,
  Terminal,
  Pause,
  RotateCcw,
  Server,
  Wifi,
  WifiOff,
  Bot,
  User,
  BookOpen,
  Cog,
  Sliders,
  GitBranch,
  Clock,
  PlusCircle,
  type LucideProps,
} from "lucide-react";

// CrystalIcon is a special case — alias to Gem since lucide doesn't have one
import { Gem as CrystalIconComp } from "lucide-react";
export const CrystalIcon = CrystalIconComp;
